# Site settings
title: Esistgut
email: g.graziosi@gmail.com
description: "Giacomo Graziosi's log about programming, embedded hardware, digital art and other random tech stuff."
keywords: [programming, development, web development, django, python, ruby, php]
baseurl: ""
url: "http://esistgut.github.io"
author: Giacomo Graziosi
twitter_username: GiacomoGraziosi
facebook_username: GiacomoGraziosi
googleplus_username: GiacomoGraziosi
github_username:  esistgut

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
#highlighter: pygments
excerpt_separator: "<!--more-->"
paginate: 5

gems:
 - jemoji
 - jekyll-sitemap
 - jekyll-redirect-from

